services:
  eureka-server:
    container_name: eureka-server
    build: ./server
    image: eureka-server:latest
    ports:
      - "19090:19090"
    networks:
      - app-network

  gateway:
    container_name: gateway
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "19091:19091"
    depends_on:
      - eureka-server
    networks:
      - app-network

  user-service:
    container_name: user-service
    build:
      context: ./user
      dockerfile: Dockerfile
    ports:
      - "19092:19092"
    depends_on:
      - eureka-server
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-db:5432/userdb

  user-db:
    container_name: user-db
    image: postgres:13
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: systempass
    ports:
      - "5432:5432"
    networks:
      - app-network

  core-service:
    container_name: core-service
    build:
      context: ./core
      dockerfile: Dockerfile
    ports:
      - "19093:19093"
    depends_on:
      - eureka-server
      - core-redis
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://core-db:5432/coredb
      REDIS_HOST: core-redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: systempass

  core-db:
    container_name: core-db
    image: postgres:13
    environment:
      POSTGRES_DB: coredb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: systempass
    ports:
      - "5433:5432"
    networks:
      - app-network

  core-redis:
    container_name: core-redis
    image: redis:latest
    command: redis-server --requirepass systempass
    ports:
      - "6379:6379"
    networks:
      - app-network

  delivery-service:
    container_name: delivery-service
    build:
      context: ./delivery
      dockerfile: Dockerfile
    ports:
      - "19097:19097"
    depends_on:
      - eureka-server
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://delivery-db:5432/deliverydb
      REDIS_HOST: delivery-redis
      REDIS_PORT: 6380
      REDIS_PASSWORD: systempass

  delivery-db:
    container_name: delivery-db
    image: postgres:13
    environment:
      POSTGRES_DB: deliverydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: systempass
    ports:
      - "5437:5432"
    networks:
      - app-network

  slack-service:
    container_name: slack-service
    build:
      context: ./slack
      dockerfile: Dockerfile
    ports:
      - "19098:19098"
    depends_on:
      - eureka-server
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://slack-db:5432/slackdb

  slack-db:
    container_name: slack-db
    image: postgres:13
    environment:
      POSTGRES_DB: slackdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: systempass
    ports:
      - "5438:5432"
    networks:
      - app-network

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - app-network

  order-service:
    container_name: order-service
    build:
      context: ./order
      dockerfile: Dockerfile
    ports:
      - "19094:19094"
    depends_on:
      - eureka-server
      - order-db
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://order-db:5432/orderdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: systempass

  order-db:
    container_name: order-db
    image: postgres:13
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: systempass
    ports:
      - "5439:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
