version: '3.8'
services:
  eureka-server:
    image: eureka-server:latest
    ports:
      - "19090:19090"
    networks:
      - app-network

  gateway:
    image: gateway:latest
    ports:
      - "19091:19091"
    depends_on:
      - eureka-server

  user-service:
    image: user-service:latest
    ports:
      - "19092:19092"
    networks:
      - app-network
    depends_on:
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-db:5432/userdb
  user-db:
    image: postgres:13
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: systempass
    ports:
      - "5432:5432"
    networks:
      - app-network

  hub-service:
    image: hub-service:latest
    ports:
      - "19093:19093"
    networks:
      - app-network
    depends_on:
      - eureka-server
      - hub-redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://hub-db:5433/hubdb
      REDIS_HOST: hub-redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: systempass
  hub-db:
    image: postgres:13
    environment:
      POSTGRES_DB: hubdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: systempass
    ports:
      - "5433:5433"
    networks:
      - app-network
  hub-redis:
    image: redis:latest
    command: redis-server --requirepass systempass
    ports:
      - "6379:6379"
    networks:
      - app-network

  company-service:
    image: company-service:latest
    ports:
      - "19094:19094"
    networks:
      - app-network
    depends_on:
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://company-db:5434/companydb
  company-db:
    image: postgres:13
    environment:
      POSTGRES_DB: companydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: systempass
    ports:
      - "5434:5434"
    networks:
      - app-network

  order-service:
    image: order-service:latest
    ports:
      - "19095:19095"
    networks:
      - app-network
    depends_on:
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://order-db:5435/orderdb
  order-db:
    image: postgres:13
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: systempass
    ports:
      - "5435:5435"
    networks:
      - app-network

  product-service:
    image: product-service:latest
    ports:
      - "19096:19096"
    networks:
      - app-network
    depends_on:
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://product-db:5436/productdb
  product-db:
    image: postgres:13
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: systempass
    ports:
      - "5436:5436"
    networks:
      - app-network

  delivery-service:
    image: delivery-service:latest
    ports:
      - "19097:19097"
    networks:
      - app-network
    depends_on:
      - eureka-server
      - delivery-redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://delivery-db:5437/deliverydb
      REDIS_HOST: delivery-redis
      REDIS_PORT: 6380
      REDIS_PASSWORD: systempass
  delivery-db:
    image: postgres:13
    environment:
      POSTGRES_DB: deliverydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: systempass
    ports:
      - "5437:5437"
    networks:
      - app-network
  delivery-redis:
    image: redis:latest
    command: redis-server --requirepass systempass
    ports:
      - "6380:6380"
    networks:
      - app-network

  slack-service:
    image: slack-service:latest
    ports:
      - "19098:19098"
    networks:
      - app-network
    depends_on:
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://slack-db:5438/slackdb
  slack-db:
    image: postgres:13
    environment:
      POSTGRES_DB: slackdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: systempass
    ports:
      - "5438:5438"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
